name: Dagger Pin Update
on:
    push:
        branches:
            - "renovate/**"
        paths:
            - "dagger.json"

jobs:
    update-pin:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                  persist-credentials: true
                  fetch-depth: 0

            - name: setup dagger
              uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
              with:
                  version: "0.19.8"
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

            - name: commit update
              run: |
                  dagger update
                  git add dagger.json
                  if ! git diff --cached --quiet; then
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git config user.name "github-actions[bot]"
                    git commit --amend --no-edit
                    git push --force-with-lease origin HEAD
                  fi
