name: Dagger Pin Update

on:
    push:
        branches:
            - "renovate/**"
        paths:
            - "dagger.json"

permissions:
    contents: write

jobs:
    update-pin:
        uses: moosingin3space/charmd-stack-ci/.github/workflows/dagger-update.yml@2d700e4ca7d9cb9226c805c2791ba004d9e627a2 # v1.1
        secrets:
            dagger-cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
