name: Publish

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    packages: write # zizmor: ignore[excessive-permissions]

jobs:
    publish-sha:
        name: Publish (SHA)
        uses: moosingin3space/charmd-stack-ci/.github/workflows/dagger-publish.yml@0e0160e31e429cd20cdbeb6bc588cb7ca018ea83 # v1.3.0
        with:
            call: publish --address=ghcr.io/${{ github.repository }}/sunapi:${{ github.sha }}
            registry: ghcr.io
            registry-username: ${{ github.actor }}
        secrets:
            dagger-cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}

    publish-latest:
        name: Publish (latest)
        needs: publish-sha
        uses: moosingin3space/charmd-stack-ci/.github/workflows/dagger-publish.yml@0e0160e31e429cd20cdbeb6bc588cb7ca018ea83 # v1.3.0
        with:
            call: publish --address=ghcr.io/${{ github.repository }}/sunapi:latest
            registry: ghcr.io
            registry-username: ${{ github.actor }}
        secrets:
            dagger-cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
