name: GitHub Actions Security Analysis with Zizmor

on:
    push:
        branches: [main]
    pull_request:
        branches: ["**"]
    repository_dispatch:
        types: [dagger-update-complete]

permissions:
    security-events: write

jobs:
    zizmor:
        uses: moosingin3space/charmd-stack-ci/.github/workflows/zizmor.yml@2d700e4ca7d9cb9226c805c2791ba004d9e627a2 # v1.1
